##### DEPENDENCIES

FROM --platform=linux/amd64 node:18.12-alpine AS deps
RUN apk add --no-cache libc6-compat openssl1.1-compat
WORKDIR /app

# Install dependencies based on the preferred package manager

COPY package.json package-lock.json ./

RUN npm ci

##### BUILDER

FROM --platform=linux/amd64 node:18.12-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ENV NEXT_TELEMETRY_DISABLED 1

# env vars
ARG NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY

ARG NEXT_PUBLIC_AUTH_DOMAIN
ENV NEXT_PUBLIC_AUTH_DOMAIN=$NEXT_PUBLIC_AUTH_DOMAIN

ARG NEXT_PUBLIC_PROJECT_ID
ENV NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID

ARG NEXT_PUBLIC_STORAGE_BUCKET
ENV NEXT_PUBLIC_STORAGE_BUCKET=$NEXT_PUBLIC_STORAGE_BUCKET

ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=$NEXT_PUBLIC_MESSAGING_SENDER_ID

ARG NEXT_PUBLIC_APP_ID
ENV NEXT_PUBLIC_APP_ID=$NEXT_PUBLIC_APP_ID

ARG NEXT_PUBLIC_MEASUREMENT_ID
ENV NEXT_PUBLIC_MEASUREMENT_ID=$NEXT_PUBLIC_MEASUREMENT_ID

ARG CLIENT_EMAIL
ENV CLIENT_EMAIL=$CLIENT_EMAIL

ARG PRIVATE_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY

RUN npm run build

##### RUNNER

FROM --platform=linux/amd64 node:18.12-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

ARG NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_API_KEY=$NEXT_PUBLIC_API_KEY

ARG NEXT_PUBLIC_AUTH_DOMAIN
ENV NEXT_PUBLIC_AUTH_DOMAIN=$NEXT_PUBLIC_AUTH_DOMAIN

ARG NEXT_PUBLIC_PROJECT_ID
ENV NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID

ARG NEXT_PUBLIC_STORAGE_BUCKET
ENV NEXT_PUBLIC_STORAGE_BUCKET=$NEXT_PUBLIC_STORAGE_BUCKET

ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=$NEXT_PUBLIC_MESSAGING_SENDER_ID

ARG NEXT_PUBLIC_APP_ID
ENV NEXT_PUBLIC_APP_ID=$NEXT_PUBLIC_APP_ID

ARG NEXT_PUBLIC_MEASUREMENT_ID
ENV NEXT_PUBLIC_MEASUREMENT_ID=$NEXT_PUBLIC_MEASUREMENT_ID

ARG CLIENT_EMAIL
ENV CLIENT_EMAIL=$CLIENT_EMAIL

ARG PRIVATE_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY

# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 80
ENV PORT 80

CMD ["node", "server.js"]
